const CONFIG = {
  whatsapp:   "351XXXXXXXXX",
  webhook:    "https://WEBHOOK_URL",
  siteUrl:    "https://igsolutionmkt-lang.github.io/swilan-site/",

  empresa: {
    nome:   "SWILAN CUÉNOD",
    razao:  "Empreendimentos Imobiliários, Unipessoal Lda",
    nif:    "518637891",
    morada: "Avenidas Novas, Lisboa, Portugal",
    email:  "geral@swilancuenod.pt",
  },

  imoveis: [
    {
      id:       "setubal",
      badge:    "Disponível",
      badgeEn:  "Available",
      badgeFr:  "Disponible",
      badgeEs:  "Disponible",
      badgeDe:  "Verfügbar",
      foto:     "assets/setubal.jpg",
      fotoAlt:  "Terraço privativo Penthouse Setúbal",
      tipo:     "Penthouse T3",
      local:    "Setúbal",
      preco:    "950.000 €",
      area:     "154 m²",
      quartos:  "3",
      wc:       "3",
      certif:   "A",
      entrega:  "Imediata",
      url:      "setubal.html",
    },
    {
      id:       "gaia-c",
      badge:    "Em Construção · Dez 2026",
      badgeEn:  "Under Construction · Dec 2026",
      badgeFr:  "En Construction · Déc 2026",
      badgeEs:  "En Construcción · Dic 2026",
      badgeDe:  "Im Bau · Dez 2026",
      foto:     "assets/gaia-c.jpg",
      fotoAlt:  "Planta T2 Gaia Fração C com piscina",
      tipo:     "T2 + Terraço com Piscina",
      local:    "Vila Nova de Gaia — Costa Sald'Ouro",
      preco:    "600.000 €",
      area:     "102 m² + 136 m² terraço",
      quartos:  "2",
      wc:       "2",
      certif:   "A",
      entrega:  "Dez. 2026",
      url:      "gaia.html",
    },
    {
      id:       "gaia-d",
      badge:    "Em Construção · Dez 2026",
      badgeEn:  "Under Construction · Dec 2026",
      badgeFr:  "En Construction · Déc 2026",
      badgeEs:  "En Construcción · Dic 2026",
      badgeDe:  "Im Bau · Dez 2026",
      foto:     "assets/gaia-d.jpg",
      fotoAlt:  "Planta T2 Gaia Fração D com piscina",
      tipo:     "T2 + Terraço com Piscina",
      local:    "Vila Nova de Gaia — Costa Sald'Ouro",
      preco:    "624.000 €",
      area:     "107 m² + 203 m² terraço",
      quartos:  "2",
      wc:       "2",
      certif:   "A",
      entrega:  "Dez. 2026",
      url:      "gaia.html",
    },
    {
      id:         "quarteira",
      badge:      "Disponível",
      badgeEn:    "Available",
      badgeFr:    "Disponible",
      badgeEs:    "Disponible",
      badgeDe:    "Verfügbar",
      badgeExtra: "Investimento · Algarve",
      foto:       "assets/quarteira.jpg",
      fotoAlt:    "Vista mar T1 Quarteira Algarve",
      tipo:       "T1",
      local:      "Quarteira, Algarve",
      preco:      "330.000 €",
      area:       "57 m²",
      quartos:    "1",
      wc:         "1",
      certif:     "A",
      entrega:    "Imediata",
      url:        "quarteira.html",
    },
  ],
};
